// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrfAeWqFYz-lPColSLyJZoFJXwODuCvhg',
    appId: '1:1000183825884:web:7a8554c2a2415c2b447b19',
    messagingSenderId: '1000183825884',
    projectId: 'dynamic-rcb-alerts',
    authDomain: 'dynamic-rcb-alerts.firebaseapp.com',
    storageBucket: 'dynamic-rcb-alerts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5pz8o_CgHcHkvTgfGyYVwYqaD8Lm87Q',
    appId: '1:1000183825884:android:cb5be27e75fb0cb6447b19',
    messagingSenderId: '1000183825884',
    projectId: 'dynamic-rcb-alerts',
    storageBucket: 'dynamic-rcb-alerts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnpXkS6TEogqlmsP878DxjpsLlG4VWCPA',
    appId: '1:1000183825884:ios:61c16e10250fcfd0447b19',
    messagingSenderId: '1000183825884',
    projectId: 'dynamic-rcb-alerts',
    storageBucket: 'dynamic-rcb-alerts.firebasestorage.app',
    iosBundleId: 'dev.slavis.dynamicrcbalerts',
  );
}
