-- Kraków demo data (synthetic) — official sources and resident reports for
-- a lively map from day one. Times are relative to now().
insert into public.incidents (id, layer, category, severity, status, source, title, description, address, lat, lng, reported_at, updated_at, confirmations, area_radius_meters, air_reading) values
  ('inf-001', 'infrastructure', 'power_outage', 'high', 'confirmed', 'utility', 'Brak prądu', 'Awaria kabla średniego napięcia. Bez zasilania ok. 40 budynków. Przewidywane przywrócenie: 18:30.', 'Kazimierz, ul. Józefa', 50.0515, 19.9446, now() - interval '34 minutes', now() - interval '34 minutes', 12, null, null),
  ('inf-002', 'infrastructure', 'flooding', 'high', 'confirmed', 'city19115', 'Zalane przejście podziemne', 'Woda po kostki w przejściu pod rondem. Zejścia od strony ul. Lubicz zamknięte, służby pompują.', 'Rondo Mogilskie', 50.0655, 19.96, now() - interval '18 minutes', now() - interval '18 minutes', 7, null, null),
  ('inf-003', 'infrastructure', 'water_outage', 'medium', 'confirmed', 'utility', 'Przerwa w dostawie wody', 'Planowana wymiana zasuwy. Beczkowóz przy bloku nr 7.', 'Nowa Huta, os. Centrum E', 50.0716, 20.0373, now() - interval '95 minutes', now() - interval '95 minutes', 3, null, null),
  ('inf-004', 'infrastructure', 'fallen_tree', 'medium', 'reported', 'city19115', 'Powalone drzewo na alejce', 'Konar blokuje alejkę Plant, przejście bokiem po trawie.', 'Planty, ul. Basztowa', 50.0652, 19.9405, now() - interval '9 minutes', now() - interval '9 minutes', 2, null, null),
  ('inf-005', 'infrastructure', 'traffic_lights', 'medium', 'confirmed', 'city19115', 'Nie działa sygnalizacja', 'Sygnalizacja wyłączona, ruchem kieruje policja.', 'Rondo Grunwaldzkie', 50.049, 19.93, now() - interval '52 minutes', now() - interval '52 minutes', 5, null, null),
  ('inf-006', 'infrastructure', 'heating', 'low', 'confirmed', 'utility', 'Spadek ciśnienia ciepłej wody', 'Prace na sieci ciepłowniczej, możliwe chwilowe przerwy.', 'Krowodrza, ul. Mazowiecka', 50.078, 19.917, now() - interval '140 minutes', now() - interval '140 minutes', 0, null, null),
  ('inf-007', 'infrastructure', 'road', 'low', 'reported', 'city19115', 'Zapadnięta nawierzchnia', 'Ubytek w jezdni przy przystanku, oznakowany pachołkami.', 'Podgórze, ul. Kalwaryjska', 50.042, 19.948, now() - interval '210 minutes', now() - interval '210 minutes', 1, null, null),
  ('inf-008', 'infrastructure', 'street_lights', 'low', 'resolved', 'city19115', 'Brak oświetlenia bulwaru', 'Naprawione przez ZDMK o 16:10.', 'Bulwar Czerwieński', 50.053, 19.933, now() - interval '300 minutes', now() - interval '300 minutes', 4, null, null),
  ('imgw-wind', 'weather', 'wind', 'medium', 'confirmed', 'imgw', 'Silny wiatr, 2. stopień', 'Porywy do 90 km/h od 20:00 do 06:00. Zabezpiecz rzeczy na balkonach, unikaj parków i alei z drzewami.', 'Kraków i powiat krakowski', 50.048, 19.985, now() - interval '120 minutes', now() - interval '120 minutes', 0, 9000, null),
  ('imgw-storm', 'weather', 'storm', 'low', 'reported', 'imgw', 'Burze z gradem, 1. stopień', 'Możliwe burze z opadem do 25 mm i gradem po 15:00.', 'Wieliczka i okolice', 49.987, 20.065, now() - interval '60 minutes', now() - interval '60 minutes', 0, 6000, null),
  ('res-001', 'neighbours', 'flooding', 'medium', 'confirmed', 'resident', 'Zalana ulica', 'Studzienki nie odbierają wody, auta jadą po osie.', 'ul. Lea przy Mazowieckiej', 50.073, 19.913, now() - interval '22 minutes', now() - interval '22 minutes', 6, null, null),
  ('res-002', 'neighbours', 'smoke', 'medium', 'reported', 'resident', 'Gęsty dym z komina', 'Czuć palone śmieci, dym nad całym podwórkiem.', 'Podgórze, ul. Limanowskiego', 50.043, 19.962, now() - interval '41 minutes', now() - interval '41 minutes', 2, null, null),
  ('res-003', 'neighbours', 'road', 'low', 'reported', 'resident', 'Dziura na pasie rowerowym', 'Głęboka, łatwo wpaść kołem po zmroku.', 'ul. Wielicka', 50.035, 19.985, now() - interval '75 minutes', now() - interval '75 minutes', 1, null, null),
  ('res-004', 'neighbours', 'power_outage', 'medium', 'reported', 'resident', 'Migające światło, potem brak prądu', 'Kilka klatek bez prądu, winda stoi.', 'Ruczaj, ul. Kobierzyńska', 50.023, 19.905, now() - interval '12 minutes', now() - interval '12 minutes', 3, null, null),
  ('res-005', 'neighbours', 'water_outage', 'low', 'resolved', 'resident', 'Wyciek wody z hydrantu', 'Zakręcone przez Wodociągi Miasta Krakowa.', 'ul. Starowiślna', 50.056, 19.944, now() - interval '160 minutes', now() - interval '160 minutes', 5, null, null)
on conflict (id) do nothing;

